#debug: true

logging:
  level:
    io.github.lingalone.timcaptchaservice.mapper: debug


pagehelper:
  auto-dialect: true
  close-conn: true



#mapper:
#    mappers:
##      - io.github.novaframe.data.mybatis.MyMapper
#    not-empty: false
#    identity: MYSQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tim_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ling1100
    driver-class-name: com.mysql.jdbc.Driver
    platform: all
    tomcat:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    type: com.zaxxer.hikari.HikariDataSource

  cache:
    ehcache:
      config: classpath:config/cache-config.xml
  devtools:
    livereload:
      enabled: true
#    restart:
#      exclude: mapper


#mybatis:
#    type-aliases-package: io.github.lingalone.webdevdemo.domain
#    mapper-locations: classpath:mapper/*.xml


swagger:
  versions:
    - version: 1.0
      group-name: api-1.0
      apis: ""
      regex: "/api/v1/.*"
      title: "Application API 1.0"
      description: "API 1.0 documentation"
      terms-of-service-url: ""
      license: ""
      licenseUrl: ""
      contact-name: ""
      contact-url: ""
      contact-email: ""

    - version: 2.0
      group-name: api-2.0
      apis: ""
      regex: "/api/v2/.*"
      title: "Application API 2.0"
      description: "API 2.0 documentation"
      terms-of-service-url: ""
      license: ""
      licenseUrl: ""
      contact-name: ""
      contact-url: ""
      contact-email: ""








